version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ze_delivery